I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 789, in script
    Y "Prosedur? Aku menemukan jumlah karyawan yang hanya 900, padahal seharusnya 1500!"
Exception: Sayer 'Y' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 789, in script
    Y "Prosedur? Aku menemukan jumlah karyawan yang hanya 900, padahal seharusnya 1500!"
  File "E:\Renpy\renpy-8.3.2-sdk\renpy\ast.py", line 2573, in execute
    Say.execute(self)
  File "E:\Renpy\renpy-8.3.2-sdk\renpy\ast.py", line 575, in execute
    who = eval_who(self.who, self.who_fast)
  File "E:\Renpy\renpy-8.3.2-sdk\renpy\ast.py", line 464, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'Y' is not defined.

Windows-10-10.0.22631 AMD64
Ren'Py 8.3.2.24090902
Taksopolis 1.0
Mon Dec  2 17:50:00 2024
